name: flutter_background_geolocation
description: The most sophisticated background location-tracking & geofencing module with battery-conscious motion-detection intelligence for iOS and Android.
version: 1.2.0
author: Chris Scott, Transistor Software <info@transistorsoft.com>
homepage: https://github.com/transistorsoft/flutter_background_geolocation

dependencies:
  flutter:
    sdk: flutter
  device_info: ^0.4.0
  background_fetch: ^0.2.0
  url_launcher: ^5.1.4

flutter:
  plugin:
    androidPackage: com.transistorsoft.flutter.backgroundgeolocation
    pluginClass: FLTBackgroundGeolocationPlugin

environment:
  sdk: ">=2.0.0-dev.50.0 <3.0.0"
  flutter: ">=1.2.0 <2.0.0"
